import { NextPage } from "next";
import Head from "next/head";
import Todo from "../compenents/Todo";


const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>MyToDo</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Todo/>
    </>
  );
};

export default Home;
